[project]
name = "vca-infra"
version = "0.1.0"
requires-python = ">=3.11,<3.12"
dependencies = [
    "sqlmodel",
    "psycopg2-binary",
    "alembic",
    "pydantic-settings",
    "vca-core",
    "celery",
    "google-cloud-storage>=3.7.0",
    "faster-whisper>=1.2.1",
    "wespeakerruntime>=1.0.1",
    "torch==2.4.1",
    "torchaudio==2.4.1",
    "soundfile==0.13.1",
    "av==16.1.0",
]

[tool.uv.sources]
vca-core = { workspace = true }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["vca_infra"]
