[project]
name = "vca-worker"
version = "0.1.0"
requires-python = ">=3.11,<4.0"
dependencies = [
    "celery[redis]>=5.6.2",
    "faster-whisper>=1.2.1",
    "vca-core",
    "vca-store",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["vca_worker"]
