[project]
name = "vca-api"
version = "0.1.0"
requires-python = ">=3.11,<3.12"
dependencies = [
    "fastapi[standard]",
    "pydantic-settings",
    "vca-auth",
    "vca-engine",
    "vca-infra",
]

[tool.uv.sources]
vca-auth = { workspace = true }
vca-engine = { workspace = true }
vca-infra = { workspace = true }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["vca_api"]

[tool.hatch.build.targets.wheel.shared-data]
"vca_api/templates" = "vca_api/templates"
"vca_api/static" = "vca_api/static"
