[project]
name = "vca-api"
version = "0.1.0"
requires-python = ">=3.10,<4.0"
dependencies = [
    "fastapi[standard]",
    "pydantic-settings",
    "vca-core",
    "vca-store",
]

[tool.uv.sources]
vca-core = { workspace = true }
vca-store = { workspace = true }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["vca_api"]
